### ISSUE TITLE
Getting "ACPI Error: Method parse/execution failed" during installation.

### ISSUE THREAD

**Issue by namannarula** [Drovosek01/hackintosh_HP_Pavilion_15-au028ur_i5-6200U#1]
Hi,
I've tried to install Mojave on my system with similar specs, and I'm getting this error when I click on install Mojave in clover. 

`ACPI Error: Method parse/execution failed` during installation.

This results in a "🚫" sign on the screen. 

I'm not quite sure what to do next. Also, FYI I used the LITE version of the macOS Image. The BDU did not install the clover EFI automatically. So I went on the repository and unpacked the ISO myself and copied it. 

My Laptop:-
**HP Pavilion 14-al062nr
Processor - Intel Core i5-6200U, Intel HD Graphics 520
RAM - 12GB DDR4 2133MHz
Motherboard - HP 8209 v82.27
BIOS - Insyde F.09
Storage - SanDisk 240GB SSD**

Will updating the BIOS help? Or is there anything else I should do? Thanks.

**Comment by namannarula** [comment]
Update: I updated the BIOS, still doesn't work. Same Error.

**Comment by namannarula** [comment]
Update: I used this [https://vk.com/doc183234383_511392572]() and now as soon as I try to boot to macos, my laptop restarts.

**Comment by Drovosek01** [comment]
Usually, the crossed-out circle icon is displayed when your USB ports are not working correctly. Try using the USBInjectAll kext

**Comment by namannarula** [comment]
I managed to fix this. What I figured out was that the VodooPS2Controller.kext was causing the issue. I removed that kext, and everything now works like a charm!
